<a href="https://colab.research.google.com/github/six-eyes-dev/100-days-of-ml/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EDA (Exploratory Data Analysis)

Three kinds:
1. Uni-variate ( single column/variable)
2. Bi-variate ( Two variables)
3. Multi-variate (More than two variables)

Import libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Import datasets

In [ ]:
iris = sns.load_dataset('iris')
flights = sns.load_dataset('flights')
tips = sns.load_dataset('tips')
titanic = sns.load_dataset('titanic')

In [ ]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
titanic.sample(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
206,0,3,male,32.0,1,0,15.8500,S,Third,man,True,NaN,Southampton,no,False
238,0,2,male,19.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
362,0,3,female,45.0,0,1,14.4542,C,Third,woman,False,NaN,Cherbourg,no,False
646,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
379,0,3,male,19.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True